### ISSUE TITLE
abnormal outputdirectory processing for compileJavacc

### ISSUE THREAD

**Issue by zosrothko** [johnmartel/javaccPlugin#32] opened 2016-11-17 16:46 UTC
Hi

the option outputDirectory from the DSL compileJavaCC does not work properly. Working on building JTB with gradle, one gets this issue.

The javacc file jtb.out.jj is located in src/EDU/purdue/jtb and has the option OUTPUT_DIRECTORY = "parser";
This means that javacc without any command line option will generate the Java classes in the directory
src/EDU/purdue/jtb/parser

With the script below
```
plugins {
  id "ca.coglinc.javacc" version "2.3.1"
}

apply plugin: "ca.coglinc.javacc"
apply plugin: 'java'

compileJavacc {
  inputDirectory = file('src')
  outputDirectory = file('src')
}
```
javaccPlugin generates the classes in src/EDU/purdue/jtb which is wrong

With the script below
```
plugins {
  id "ca.coglinc.javacc" version "2.3.1"
}

apply plugin: "ca.coglinc.javacc"
apply plugin: 'java'

compileJavacc {
  inputDirectory = file('src')
  outputDirectory = file('src/EDU/purdue/jtb/parser')
}
```
javaccPlugin generates the classes in src/EDU/purdue/jtb/parser/EDU/purdue/jtb which is wrong

**Comment by johnmartel** [comment] 2016-11-19 23:36
Have you tried not to set the `outputDirectory`directive at all? Generating files in the inputDirectory is not likely to give good results. The plugin uses the `OUTPUT_DIRECTORY` option to generate the files in the correct location. I recommend using the `package` directive of the jj file to set the package to `EDU.purdue.jtb.parser`, which will generate the files in the correct location under `build/generated/jjtree`. Please note that this directory is automatically added by the plugin as a source for the `compileJavacc` task.

**Comment by zosrothko** [comment] 2016-11-20 17:43
It seems you are missing a key functionnality of the output_directory option. Javacc is generating the javacc classes in the output directory specified by the -output_directory option whatever is specified the package in the jj file. As exemple taking this Parser.jj file
```
options { STATIC=false; }

PARSER_BEGIN(Parser)
package foo;
public class Parser {
  public static void main(String args[]) throws Exception {
    Parser t = new Parser(System.in);
    t.CompilationUnit();
    System.out.println("Parser ran sucessfully");
  }
}
PARSER_END(Parser)
TOKEN : {  < A: "A"> | < B: "B"> | < C: "C"> | < D: "D"> }
void CompilationUnit() : {} { 	("A" | "B" )* 	<EOF> }

```
let say the Parser.jj is located in the directory tmp.
the command line 
```
Z:\git\javacc\tmp>java -classpath ../target/javacc.jar javacc -output_directory=bar/toy/acme Parser.jj
```
will generate the classes in the directory `tmp/bar/toy/acme`whatever is the package definition in the Parser.jj. Thus, the javaccPlugin should do the same when the outputDirectory is specified in the gradle script. The resulting generated classes must be located in the specified directory.

**Comment by johnmartel** [comment] 2016-11-20 17:45
I understand this clearly, but what I'm missing is why you want to generate a java class in a directory that does not correspond to its package?

Envoyé de mon iPhone

**Comment by zosrothko** [comment] 2016-11-20 17:53
because that's the the javacc itself is build and also because that's the way jtb is build also.

**Comment by zosrothko** [comment] 2016-11-20 18:00
Moreover and as a better argument, that's the way javacc is working.

**Comment by johnmartel** [comment] 2016-11-28 01:14
Closing this issue as it is basically a duplicate of Issue #31 .

**Closed by johnmartel** 2016-11-28 01:14 UTC
